### ISSUE TITLE
Lay out PCB

### ISSUE THREAD

**Issue by amcewen** [Tactile-electronics/windmill-electronics#4]
Following on from #2, we need to work out the physical layout for the circuit.

**Comment by amcewen** [comment]
Board laid out, including copper fill zones round the parts of the charging circuit that might get warmer.  Added some mounting holes too.

Just needs some extra labels now:
* To mark inputs / outputs
* Explain jumpers (where possible)
* Add a revision number
* Add a link to this repo (plus https://tactile-electronics.tumblr.com/ and mcqn.com/ibal233)
* Add RoHS, WEEE logos
* Add OSHW logo

**Comment by amcewen** [comment]
I've finished (I think) the silkscreen labels.  Any tweaks/suggestions/etc. @Tactile-electronics, before I send off for a handful (half-a-dozen?  A dozen?) to get fabbed for testing?

![image](https://user-images.githubusercontent.com/108468/166253875-16459304-31fe-4be1-a53a-155384357625.png)

![image](https://user-images.githubusercontent.com/108468/166253982-3ab2afb7-616e-4626-9791-f3d4dc08003f.png)

**Comment by Tactile-electronics** [comment]
Oh wow ,  brilliant! I’m really excited to try them out. I would imagine
there’s not a huge amount of difference price wise so a dozen?
Is it easier for you to order them and me pay you back or the other way
around?
Thanks
Laura

**Comment by amcewen** [comment]
Great.  I've ordered 15 from JLC, and most of the parts — still need to get the bridge rectifiers and resistors (and connectors, but I'm not sure we'd want to populate them by default anyway) — from LCSC (needed to get the charger chips from there, so figured I'd order the other easy stuff at the same time)

About £60 so far (it's all in $) and half of that is postage :grin:  It'll be a couple of weeks before it arrives, I'll let you know when it gets here.
